---
directory: /backup/
freq: 1440
begin: 2330
deleteOldFilesAfter: 5
debug: false

# Use nfs mount directly without pv / pvc
raw_nfs:
  enabled: false
  path: /PRD_LNX_K8S01_003
  server: nfs.local.dmz
  readonly: false

# Use claim for backups. `raw_nfs.enabled` should be false
persistence:
  enabled: false
  storageClassName: manual
  storageSize: 10Gi
