---
image: lachlanevenson/k8s-helm:latest

stages:
  - test
  - build

lint:
  stage: test
  script:
    - find ./charts -type d -maxdepth 1  -not -path ./charts -print0 | xargs -0 -n 1 helm lint

package:
  stage: build
  script:
    - ./build.sh
