global:
  ## NodeSelector to be used in every deployment
  ## hub, chrome, firefox, chromeDebug and firefoxDebug
  ## can also be spceifed at chart level see below
  nodeSelector:
  #  label: value

browsermob:
  ## The repository and image
  ## ref: https://hub.docker.com/r/qautomatron/docker-browsermob-proxy/
  image: "qautomatron/docker-browsermob-proxy"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/qautomatron/docker-browsermob-proxy/tags/
  tag: "2.1.3"

  ## Specify an imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: "IfNotPresent"

  ## The port which the browsermob listens on
  port: 9090

  ## Proxy port range
  proxyPorts:
    - 39500
    - 39501
    - 39502
    - 39503
    - 39504
    - 39505
    - 39506
    - 39507
    - 39508
    - 39509
    - 39510
    - 39511
    - 39512
    - 39513
    - 39514
    - 39515
    - 39516
    - 39517
    - 39518
    - 39519
    - 39520
    - 39521
    - 39522
    - 39523
    - 39524
    - 39525
    - 39526
    - 39527
    - 39528
    - 39529
    - 39530
    - 39531
    - 39532
    - 39533
    - 39534
    - 39535
    - 39536
    - 39537
    - 39538
    - 39539
    - 39540
    - 39541
    - 39542
    - 39543
    - 39544
    - 39545
    - 39546
    - 39547
    - 39548
    - 39549
    - 39550
    - 39551
    - 39552
    - 39553
    - 39554
    - 39555
    - 39556
    - 39557
    - 39558
    - 39559
    - 39560
    - 39561
    - 39562
    - 39563
    - 39564
    - 39565
    - 39566
    - 39567
    - 39568
    - 39569
    - 39570
    - 39571
    - 39572
    - 39573
    - 39574
    - 39575
    - 39576
    - 39577
    - 39578
    - 39579
    - 39580
    - 39581
    - 39582
    - 39583
    - 39584
    - 39585
    - 39586
    - 39587
    - 39588
    - 39589
    - 39590
    - 39591
    - 39592
    - 39593
    - 39594
    - 39595
    - 39596
    - 39597
    - 39598
    - 39599

  ## Timeout for probe Browsermob readiness via HTTP request on Browsermob proxy list
  readinessTimeout: 1

  ## Timeout for probe Browsermob liveness via HTTP request on Browsermob proxy list
  livenessTimeout: 1

  ## Set the JAVA_TOOL_OPTIONS environment variable
  javaOpts: "-Xmx400m"

  ## Defining a JMX port will open the port on the container, however, it
  ## requires additional javaOpts, ie
  ## javaOpts: >
  ##   -Dcom.sun.management.jmxremote.port=4000
  ##   -Dcom.sun.management.jmxremote.authenticate=false
  ##   -Dcom.sun.management.jmxremote.ssl=false
  ## ref: http://openjdk.java.net/groups/jmx/
  # jmxPort: 4000

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: ".5"
      memory: "512Mi"

  ## The type of service to create
  ##   Values: ClusterIP, NodePort, LoadBalancer, or ExternalName
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceType: "NodePort"

  ## The LoadBalancer IP Address
  ## ref: https://kubernetes.io/docs/user-guide/services/
  ## serviceLoadBalancerIP: "40.121.183.52"

  ## Control where client requests go, to the same pod or round-robin
  ##   Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceSessionAffinity: "ClientIP"

  ## Define various attributes of the service
  # serviceAnnotations:
  #   # internal AWS ELB
  #   service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"

  # timeZone: UTC

  ## NodeSelector to be used for the browsermob
  nodeSelector:
  #  label: value
