{{- if .Values.persistence.gitlabBuilds.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab-ce.fullname" . }}-builds
  annotations:
spec:
  {{- if .Values.persistence.gitlabData.storageClass }}
  storageClassName: {{ .Values.persistence.gitlabBuilds.storageClass | quote }}
  {{- else }}
  storageClassName: default
  {{- end }}
  accessModes:
    - {{ .Values.persistence.gitlabBuilds.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabBuilds.size | quote }}
{{- end }}
