apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.gitlabRootPassword }}
  gitlab-root-password: {{ .Values.gitlabRootPassword | b64enc | quote }}
  {{- else }}
  gitlab-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
