apiVersion: v1
kind: Service
metadata:
  name: {{ template "browsermob.browsermob.fullname" . }}
  labels:
    app: {{ template "browsermob.browsermob.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.browsermob.serviceAnnotations }}
  annotations:
{{ toYaml .Values.browsermob.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.browsermob.serviceType | quote }}
  {{- if .Values.browsermob.serviceLoadBalancerIP }}
  loadBalancerIP: {{ .Values.browsermob.serviceLoadBalancerIP | quote }}
  {{- end }}
  sessionAffinity: {{ .Values.browsermob.serviceSessionAffinity | quote }}
  ports:
    - name: http
      protocol: "TCP"
      port: {{ .Values.browsermob.port }}
      targetPort: {{ .Values.browsermob.port }}
    {{- range $index, $port := .Values.browsermob.proxyPorts  }}
    - name: proxy-{{ $index }}
      protocol: "TCP"
      port: {{ $port }}
    {{- end }}
  selector:
    app: {{ template "browsermob.browsermob.fullname" . }}
