
konga:
  image:
    repository: pantsel/konga
    tag: 0.11.0
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  class: ""
  domain: paas-prod01.local.dmz

postgres:
  postgresUser: konga
  postgresPassword: konga
  postgresDatabase: konga
  persistence:
    enabled: true
    storageClass: "-"
  metrics:
    enabled: false
