apiVersion: v1
kind: Secret
metadata:
  name: {{ template "staytus.fullname" . }}
  labels:
    app: {{ template "staytus.name" . }}
    chart: {{ template "staytus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mariadb.db.password }}
  mariadb-password: "{{ .Values.mariadb.db.password | b64enc }}"
  {{- else if (not .Values.mariadb.db.forcePassword) }}
  mariadb-password: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.mariadb.db.password }}
  {{- end }}
  {{- if .Values.smtp.enabled }}
  {{- if .Values.smtp.password }}
  smtp-password: "{{ .Values.smtp.password | b64enc }}"
  {{- else }}
  smtp-password: {{ required "An SMTP Password is required!" .Values.smtp.password }}
  {{- end }}
  {{- end }}
