---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kong-ingress-controller.fullname" . }}-kong
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ template "kong-ingress-controller.name" . }}
    chart: {{ template "kong-ingress-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kong-ingress-controller.name" . }}-kong
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-kong-proxy
        image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
        imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
        env:
          - name: KONG_PG_USER
            value: {{ .Values.postgres.user }}
          - name: KONG_PG_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: KONG_PG_HOST
            value: {{ template "kong-ingress-controller.name" . }}-postgres
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_LISTEN
            value: 'off'
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
