---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong-ingress.fullname" . }}-kong
  labels:
    app: {{ template "kong-ingress.name" . }}
    chart: {{ template "kong-ingress.chart" . }}
    component: kong
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.kong.service.type }}
  {{- if and (eq .Values.kong.service.type "LoadBalancer") .Values.ingress.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kong.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: kong-proxy
    {{- if (eq .Values.kong.service.type "NodePort") }}
    nodePort: {{ default 80 .Values.kong.service.http_port }}
    {{- end}}
    port: 80
    targetPort: 80
    protocol: TCP
  - name: kong-proxy-ssl
    {{- if (eq .Values.kong.service.type "NodePort") }}
    nodePort: {{ default 443 .Values.kong.service.https_port }}
    {{- end}}
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: {{ template "kong-ingress.name" . }}
    component: kong
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kong-ingress.fullname" . }}-kong
  labels:
    app: {{ template "kong-ingress.name" . }}
    component: kong
    chart: {{ template "kong-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "kong-ingress.name" . }}
      component: kong
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kong-ingress.name" . }}
        component: kong
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-kong-proxy
        image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
        imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
        env:
          - name: KONG_PG_USER
            value: {{ .Values.postgresql.postgresUser }}
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "postgresql.secretName" . }}-postgresql
                key: postgres-password
          - name: KONG_PG_HOST
            value: {{ template "kong-ingress.name" . }}-postgresql
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_LISTEN
            value: "off"
          {{- range $key, $value := .Values.kong.config }}
          - name: KONG_{{ $key | upper }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - name: proxy
          containerPort: 80
          protocol: TCP
        - name: proxy-ssl
          containerPort: 443
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
