---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong-ingress.name" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "kong-ingress.name" . }}
    chart: {{ template "kong-ingress.chart" . }}
    component: postgres
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: {{ template "kong-ingress.name" . }}
    component: postgres
    release: {{ .Release.Name }}
---
apiVersion: apps/v1  #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "kong-ingress.name" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ template "kong-ingress.name" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kong-ingress.name" . }}
      component: postgres
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kong-ingress.name" . }}
        component: postgres
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
