dependencies:
- name: redis
  version: ~1.1.20
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: ~0.9.3
  repository: https://kubernetes-charts.storage.googleapis.com/
