replicaCount: 1

kong:
  image:
    repository: kong
    tag: 0.13.1-centos
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    loadBalancerIP: ""
    http_port: 80
    https_port: 443
  config: {}

ingress:
  image:
    repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    tag: 0.0.4
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    loadBalancerIP: ""
    port: 8001

postgres:
  postgresUser: kong
  postgresPassword:
  postgresDatabase: kong
  persistence:
    enabled: true
    storageClass: "-"
  metrics:
    enabled: false

  image:
    repository: postgres
    tag: 9.5
    pullPolicy: IfNotPresent

customtypes:
  # Enable CustomResourceDefinitions - If you deploy multiple ingress controllers
  # to your cluster, those have to be deployed only once.
  enabled: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
